del ..\scripts\!init.anarkis.modified.xml
del ..\scripts\al.Anarkis.ECS.Hotkey.Install.xml
del ..\scripts\al.Anarkis.ECS.Hotkey.Remove.xml
del ..\scripts\al.Anarkis.ECS.Init.xml
del ..\scripts\al.Anarkis.ECS.Main.xml
del ..\scripts\al.Anarkis.ECS.Stop.xml
del ..\scripts\al.plugin.Anarkis.ECS.xml
del ..\scripts\Cmd.Anarkis.Attack.xml
del ..\scripts\Cmd.Anarkis.AttackLand.xml
del ..\scripts\Cmd.Anarkis.Jump.xml
del ..\scripts\Cmd.Anarkis.Protect.xml
del ..\scripts\Cmd.Anarkis.Refuel.xml
del ..\scripts\Cmd.Anarkis.Wing.Ship.MoveFormation.xml
del ..\scripts\HK.Anarkis.ECS.Comm.Plugin.xml
del ..\scripts\HK.Anarkis.ECS.PluginExample.Comm.xml
del ..\scripts\Lib.Cmd.Anarkis.AttackSame.xml
del ..\scripts\Lib.Cmd.Anarkis.Dock.All.xml
del ..\scripts\Lib.Cmd.Anarkis.Dock.Custom.xml
del ..\scripts\Lib.Cmd.Anarkis.DockAll.ADSonly.xml
del ..\scripts\Lib.Cmd.Anarkis.DockAll.InSector.xml
del ..\scripts\Lib.Cmd.Anarkis.DockAll.Secure.xml
del ..\scripts\Lib.Cmd.Anarkis.DockCustom.Secure.xml
del ..\scripts\Lib.Cmd.Anarkis.DoNothing.xml
del ..\scripts\Lib.Cmd.Anarkis.Formation.Cohesion.xml
del ..\scripts\Lib.Cmd.Anarkis.JumpMove.xml
del ..\scripts\Lib.Cmd.Anarkis.JumpNearObject.xml
del ..\scripts\Lib.Cmd.Anarkis.JumpToBeacon.xml
del ..\scripts\Lib.Cmd.Anarkis.KillAndLand.Timeout.xml
del ..\scripts\Lib.Cmd.Anarkis.MoveToSafeStation.xml
del ..\scripts\Lib.Cmd.Anarkis.Task.Autodocking.xml
del ..\scripts\Lib.Cmd.Anarkis.Task.Autosupply.xml
del ..\scripts\Lib.Cmd.Anarkis.Wing.MoveFormation.xml
del ..\scripts\Lib.Cmd.Anarkis.Wing.Peace.xml
del ..\scripts\Lib.Cmd.Anarkis.Wing.War.xml
del ..\scripts\Lib.Debug.Anarkis.Output.Log.xml
del ..\scripts\Lib.Debug.Anarkis.Test.1.xml
del ..\scripts\Lib.Gen.Anarkis.Add.Software.xml
del ..\scripts\Lib.Gen.Anarkis.ArmShip.xml
del ..\scripts\Lib.Gen.Anarkis.ArmTurret.xml
del ..\scripts\Lib.Gen.Anarkis.Arrays.Sort.xml
del ..\scripts\Lib.Gen.Anarkis.Build.Ships.xml
del ..\scripts\Lib.Gen.Anarkis.Calc.Dist.xml
del ..\scripts\Lib.Gen.Anarkis.Check.JumpError.xml
del ..\scripts\Lib.Gen.Anarkis.Clear.ShipArray.xml
del ..\scripts\Lib.Gen.Anarkis.Create.Factory.xml
del ..\scripts\Lib.Gen.Anarkis.Create.Marine.xml
del ..\scripts\Lib.Gen.Anarkis.Create.Passenger.xml
del ..\scripts\Lib.Gen.Anarkis.Create.Ship.xml
del ..\scripts\Lib.Gen.Anarkis.Crew.Member.Train.xml
del ..\scripts\Lib.Gen.Anarkis.CustOwned.AddShip.xml
del ..\scripts\Lib.Gen.Anarkis.CustOwned.CleanArr.F.xml
del ..\scripts\Lib.Gen.Anarkis.CustOwned.CleanArray.xml
del ..\scripts\Lib.Gen.Anarkis.CustOwned.GetArray.F.xml
del ..\scripts\Lib.Gen.Anarkis.CustOwned.GetArray.xml
del ..\scripts\Lib.Gen.Anarkis.CustOwned.GetDocked.xml
del ..\scripts\Lib.Gen.Anarkis.CustOwned.Init.xml
del ..\scripts\Lib.Gen.Anarkis.CustOwned.Kill.xml
del ..\scripts\Lib.Gen.Anarkis.Disable.AI.xml
del ..\scripts\Lib.Gen.Anarkis.Dock.Repair.Array.xml
del ..\scripts\Lib.Gen.Anarkis.ECS.Comm.Plugin.xml
del ..\scripts\Lib.Gen.Anarkis.ECS.News.Add.xml
del ..\scripts\Lib.Gen.Anarkis.ECS.News.Clear.xml
del ..\scripts\Lib.Gen.Anarkis.ECS.News.GetRandom.xml
del ..\scripts\Lib.Gen.Anarkis.ECS.Plugin.Register.xml
del ..\scripts\Lib.Gen.Anarkis.ECS.Plugin.Unregister.xml
del ..\scripts\Lib.Gen.Anarkis.Encyclopedia.Chapter.xml
del ..\scripts\Lib.Gen.Anarkis.Encyclopedia.xml
del ..\scripts\Lib.Gen.Anarkis.Get.ByCargoValue.Adv.xml
del ..\scripts\Lib.Gen.Anarkis.Get.ByCargoValue.Fro.xml
del ..\scripts\Lib.Gen.Anarkis.Get.DockedOwned.xml
del ..\scripts\Lib.Gen.Anarkis.Get.Military.Array.xml
del ..\scripts\Lib.Gen.Anarkis.Get.MilitaryBase.xml
del ..\scripts\Lib.Gen.Anarkis.Get.PlSector.PerShip.xml
del ..\scripts\Lib.Gen.Anarkis.Get.PlSector.xml
del ..\scripts\Lib.Gen.Anarkis.Get.Race.Array.xml
del ..\scripts\Lib.Gen.Anarkis.Get.RaceSectors.xml
del ..\scripts\Lib.Gen.Anarkis.Get.Random.Pos.From.xml
del ..\scripts\Lib.Gen.Anarkis.Get.Random.Pos.xml
del ..\scripts\Lib.Gen.Anarkis.Get.RelationToPoints.xml
del ..\scripts\Lib.Gen.Anarkis.Get.Rnd.Race.xml
del ..\scripts\Lib.Gen.Anarkis.Get.Sector.Plus.xml
del ..\scripts\Lib.Gen.Anarkis.Get.Ship.CargoValue.xml
del ..\scripts\Lib.Gen.Anarkis.Get.ShipCount.xml
del ..\scripts\Lib.Gen.Anarkis.Get.ShipList.From.SY.xml
del ..\scripts\Lib.Gen.Anarkis.Get.Ships.Fast.xml
del ..\scripts\Lib.Gen.Anarkis.Get.Ships.Var.xml
del ..\scripts\Lib.Gen.Anarkis.Get.Shipyard.xml
del ..\scripts\Lib.Gen.Anarkis.Get.WingNames.xml
del ..\scripts\Lib.Gen.Anarkis.Guild.ChangeScore.xml
del ..\scripts\Lib.Gen.Anarkis.Guild.GetScore.xml
del ..\scripts\Lib.Gen.Anarkis.Guild.IsGuild.xml
del ..\scripts\Lib.Gen.Anarkis.Guild.Join.xml
del ..\scripts\Lib.Gen.Anarkis.Guild.Register.xml
del ..\scripts\Lib.Gen.Anarkis.Guild.Remove.xml
del ..\scripts\Lib.Gen.Anarkis.Id.To.Race.xml
del ..\scripts\Lib.Gen.Anarkis.Kcnt.Add.xml
del ..\scripts\Lib.Gen.Anarkis.Kcnt.FindTop.xml
del ..\scripts\Lib.Gen.Anarkis.Kcnt.Get.xml
del ..\scripts\Lib.Gen.Anarkis.Kcnt.Init.xml
del ..\scripts\Lib.Gen.Anarkis.Kcnt.Kill.xml
del ..\scripts\Lib.Gen.Anarkis.Kcnt.Set.xml
del ..\scripts\Lib.Gen.Anarkis.Kill.Civilians.Sector.xml
del ..\scripts\Lib.Gen.Anarkis.Kill.Civilians.xml
del ..\scripts\Lib.Gen.Anarkis.Kill.Task.xml
del ..\scripts\Lib.Gen.Anarkis.Race.To.Id.xml
del ..\scripts\Lib.Gen.Anarkis.Restore.Signals.xml
del ..\scripts\Lib.Gen.Anarkis.RevealMap.xml
del ..\scripts\Lib.Gen.Anarkis.Ship.Sort.xml
del ..\scripts\Lib.Gen.Anarkis.ShipState.Restore.xml
del ..\scripts\Lib.Gen.Anarkis.ShipState.Save.xml
del ..\scripts\Lib.Gen.Anarkis.ShipType.Array.M3M4.xml
del ..\scripts\Lib.Gen.Anarkis.ShortCmd.xml
del ..\scripts\Lib.Gen.Anarkis.ShortString.xml
del ..\scripts\Lib.Gen.Anarkis.Vis.BlinkName.xml
del ..\scripts\Lib.Gen.Anarkis.Vis.ShowText.xml
del ..\scripts\Lib.Gen.Anarkis.Vis.Task.Blink.xml
del ..\scripts\Lib.Gen.Anarkis.Vis.Task.ShowText.xml
del ..\scripts\Lib.Gen.Anarkis.Wait.NotRnd.xml
del ..\scripts\Lib.Gen.Anarkis.Wait.Random.xml
del ..\scripts\Lib.Gen.Anarkis.Wait.xml
del ..\scripts\Lib.Gen.Anarkis.Wing.ChangeLeader.xml
del ..\scripts\Lib.Gen.Anarkis.Wing.GetAll.xml
del ..\scripts\Lib.Gen.Anarkis.Wing.Join.xml
del ..\scripts\Lib.Gen.Anarkis.Wing.Split.xml
del ..\scripts\Menu.Anarkis.ECS.Dialog.Menu.xml
del ..\scripts\Menu.Anarkis.ECS.Dialog.Ok.xml
del ..\scripts\Menu.Anarkis.ECS.Dialog.YesNo.xml
del ..\scripts\Menu.Anarkis.ECS.Manager.SM.xml
del ..\scripts\Menu.Anarkis.ECS.Manager.xml
del ..\scripts\Menu.Anarkis.ECS.News.Display.SM.xml
del ..\scripts\Menu.Anarkis.ECS.News.Display.xml
del ..\scripts\Menu.Anarkis.Lib.Ask.ShipArray.SM.xml
del ..\scripts\Menu.Anarkis.Lib.Ask.ShipArray.xml
del ..\scripts\Menu.Anarkis.Lib.Display.Message.xml
del ..\scripts\plugin.Anarkis.ECS.PluginExample.Comm.xml
del ..\scripts\plugin.Anarkis.ECS.PluginExample.Register.xml
del ..\scripts\plugin.Anarkis.ECS.PluginExample.Remove.xml
del ..\scripts\plugin.Anarkis.ECS.PluginExample.Setup.xml
del ..\scripts\plugin.Anarkis.ECS.PluginExample.Uninstall.xml
del ..\t\8511-L033.xml
del ..\t\8511-L044.xml
del ..\t\8511-L048.xml
del ..\t\8511-L049.xml